#!/opt/homebrew/bin/bash

flag=0
n=$'\n'

if [ "$1" ]; then
  tests=("$1")
else
  tests=($(seq 1 25))
fi

for i in ${tests[@]}; do
  if [ -d "Day$i" ]; then
    ans1=$(runhaskell "$PWD/Day$i/main.hs" "$PWD/Day$i/test.txt")
    ans3=$(runhaskell "$PWD/Day$i/main.hs" "$PWD/Day$i/input.txt")
    if [ -f "$PWD/Day$i/test2.txt" ]; then
      ans2=$(runhaskell "$PWD/Day$i/main.hs" "$PWD/Day$i/test2.txt")
      ans="$ans1$n$ans2$n$ans3"
    else
      ans="$ans1$n$ans3"
    fi
    if [ -f "$PWD/Day$i/answer.txt" ]; then
      saved=$(cat "$PWD/Day$i/answer.txt")
      if [ "$ans" != "$saved" ]; then
        echo -e "Day $i incorrect:\n$(diff -u <(echo -e "$ans") <(echo -e "$saved"))"
        flag=1
      else
        echo "Day $i correct"
      fi
    else
      echo "Day $i has no answer. Forgot to run './run $i -s'?"
      flag=1
    fi
  fi
done

exit $flag
