name:                aoc2022
version:             0.1.0.0
github:              "Josh-Cena/aoc2022"

dependencies:
- base >= 4.7 && < 5
- containers
- text
- ghc

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-incomplete-uni-patterns
- -Wno-name-shadowing

executables:
  aoc2022:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - ImportQualifiedPost
    - MultiWayIf
    - NamedFieldPuns
    - NumericUnderscores
    - TupleSections
