#!/opt/homebrew/bin/bash

echo "Test:"
ans1=$(runhaskell "$PWD/Day$1/main.hs" "$PWD/Day$1/test.txt")
echo "$ans1"

if [ -f "$PWD/Day$1/test2.txt" ]; then
  echo -e "\nTest2:"
  ans2=$(runhaskell "$PWD/Day$1/main.hs" "$PWD/Day$1/test2.txt")
  echo "$ans2"
fi

if [ "$2" != "-t" ]; then
  echo -e "\nReal:"
  ans3=$(runhaskell "$PWD/Day$1/main.hs" "$PWD/Day$1/input.txt")
  echo "$ans3"
fi

[[ $ans2 ]] && ans="$ans1\n$ans2\n$ans3" || ans="$ans1\n$ans3"

if [ "$2" = "-s" ]; then
  echo -e "$ans" > "$PWD/Day$1/answer.txt"
fi
